### ISSUE TITLE
Better behaviour if wrong set_amount is given

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [alcubierre-drive/backlight-tooler#2]
When a user gives a too high brightness value (e.g. 4000 where the maximum is 1000), the [program](https://github.com/alcubierre-drive/backlight-tooler/blob/master/main.c#L245) currently defaults to the default value.

Instead it should default to the maximum value. You could change [Line 245 of main.c](https://github.com/alcubierre-drive/backlight-tooler/blob/master/main.c#L245) to handle both cases separately and

* if `amount > maxbr` set to `return maxbr`
* if `amount < 0` just exit and don't do anything.

**Comment by alcubierre-drive** [comment]
I see that it is inconvenient behaviour to default to an arbitrary (but configurable) value. A reasonable solution is probably nontrivial, but I will take this into account when working on the code the next time.
