### ISSUE TITLE
Feature request: Add a possibility use relative brightness

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [alcubierre-drive/backlight-tooler#4]
`backlight-tooler inc` currently only accepts absolute values. It would be nice of it could also accept percentages (maybe including a `%` sign) so you don't need to know your max brightness by heart. Same goes for the `dec` and `set` options.

**Comment by alcubierre-drive** [comment]
Fixed in the current version. You might want to test it so I can close the issue.

**Comment by Stefan-Heimersheim** [comment]
Awesome, it works great!
