### ISSUE TITLE
Feature Request: Make backlight-tooler info show current brightness

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [alcubierre-drive/backlight-tooler#5]
`backlight-tooler info` currently only displays the webcam light level. It would be useful to also show the current brightness and maybe further information such as max_brightness.

Example:

    [info] Current webcam light level: 156
    [info] Current display brightness: 1500
    [info] Maximum display brightness: 3000

**Comment by alcubierre-drive** [comment]
Fixed in the current version.
